name: open_nizvpn
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  avatar_glow: ^2.0.1
  circular_check_box: ^1.0.4
  roundcheckbox: ^2.0.2+1
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.7
  #flutter_openvpn: ^0.2.0
  animator: ^3.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  package_info: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - "assets/"
    - "assets/vpn/"
    - "assets/src/"